CREATE TABLE "ambienti" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "materiali" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "marche" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL,
  "logo_url" varchar(255),
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "partita_iva" varchar(20),
  "telefono" varchar(20),
  "sito_web" varchar(255),
  "attivo" boolean DEFAULT false,
  "data_registrazione" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "ultimo_accesso" timestamp
);

CREATE TABLE "prodotti" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "marca_id" int NOT NULL,
  "nome" varchar(200) NOT NULL,
  "descrizione" text,
  "certificazioni" varchar(255),
  "resistenza" varchar(255),
  "base" varchar(50),
  "numero_mani" int,
  "temperatura_applicazione" varchar(100),
  "copertura_per_litro" decimal(5,2),
  "scheda_tecnica_url" varchar(255),
  "approvato" boolean DEFAULT false,
  "data_creazione" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "data_modifica" timestamp
);

CREATE TABLE "prodotti_ambienti_materiali" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prodotto_id" int NOT NULL,
  "ambiente_id" int NOT NULL,
  "materiale_id" int NOT NULL
);

CREATE TABLE "colori" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prodotto_id" int NOT NULL,
  "nome" varchar(100) NOT NULL,
  "codice_hex" char(7) NOT NULL
);

CREATE TABLE "dimensioni" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "litri" decimal(3,1) UNIQUE NOT NULL
);

CREATE TABLE "prezzi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "colore_id" int NOT NULL,
  "dimensione_id" int NOT NULL,
  "prezzo" decimal(8,2) NOT NULL
);

CREATE TABLE "ruoli" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "utenti" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ruolo_id" int NOT NULL DEFAULT 3,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "nome" varchar(100) NOT NULL,
  "cognome" varchar(100) NOT NULL,
  "attivo" boolean DEFAULT true,
  "data_registrazione" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "ultimo_accesso" timestamp
);

CREATE TABLE "preferiti" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "utente_id" int NOT NULL,
  "prodotto_id" int NOT NULL,
  "data_aggiunta" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE UNIQUE INDEX ON "prodotti_ambienti_materiali" ("prodotto_id", "ambiente_id", "materiale_id");

CREATE UNIQUE INDEX ON "prezzi" ("colore_id", "dimensione_id");

CREATE UNIQUE INDEX ON "preferiti" ("utente_id", "prodotto_id");

COMMENT ON COLUMN "ambienti"."nome" IS 'Interno o Esterno';

COMMENT ON COLUMN "materiali"."nome" IS 'Legno, Cemento, Metallo, ecc.';

COMMENT ON COLUMN "marche"."logo_url" IS 'URL del logo della marca';

COMMENT ON COLUMN "marche"."email" IS 'Email per login della marca';

COMMENT ON COLUMN "marche"."password_hash" IS 'Password criptata con bcrypt';

COMMENT ON COLUMN "marche"."partita_iva" IS 'P.IVA della marca';

COMMENT ON COLUMN "marche"."attivo" IS 'Richiede approvazione admin';

COMMENT ON COLUMN "prodotti"."certificazioni" IS 'es. Ecolabel, A+';

COMMENT ON COLUMN "prodotti"."resistenza" IS 'es. Antimuffa, Lavabile, UV';

COMMENT ON COLUMN "prodotti"."base" IS 'Acqua o Solvente';

COMMENT ON COLUMN "prodotti"."numero_mani" IS 'Numero di mani consigliate';

COMMENT ON COLUMN "prodotti"."temperatura_applicazione" IS 'es. +5°C / +30°C';

COMMENT ON COLUMN "prodotti"."copertura_per_litro" IS 'mq per litro';

COMMENT ON COLUMN "prodotti"."scheda_tecnica_url" IS 'Link al PDF della scheda tecnica';

COMMENT ON COLUMN "prodotti"."approvato" IS 'Richiede approvazione admin prima di essere visibile';

COMMENT ON COLUMN "colori"."nome" IS 'es. Bianco Puro, Rosso Ferrari';

COMMENT ON COLUMN "colori"."codice_hex" IS 'es. #FFFFFF';

COMMENT ON COLUMN "dimensioni"."litri" IS '0.5, 1, 2, 5, 10';

COMMENT ON COLUMN "ruoli"."nome" IS 'admin, marca, o user';

COMMENT ON COLUMN "utenti"."ruolo_id" IS 'Default: user';

COMMENT ON COLUMN "utenti"."password_hash" IS 'Password criptata con bcrypt';

ALTER TABLE "prodotti" ADD FOREIGN KEY ("marca_id") REFERENCES "marche" ("id");

ALTER TABLE "prodotti_ambienti_materiali" ADD FOREIGN KEY ("prodotto_id") REFERENCES "prodotti" ("id");

ALTER TABLE "prodotti_ambienti_materiali" ADD FOREIGN KEY ("ambiente_id") REFERENCES "ambienti" ("id");

ALTER TABLE "prodotti_ambienti_materiali" ADD FOREIGN KEY ("materiale_id") REFERENCES "materiali" ("id");

ALTER TABLE "colori" ADD FOREIGN KEY ("prodotto_id") REFERENCES "prodotti" ("id");

ALTER TABLE "prezzi" ADD FOREIGN KEY ("colore_id") REFERENCES "colori" ("id");

ALTER TABLE "prezzi" ADD FOREIGN KEY ("dimensione_id") REFERENCES "dimensioni" ("id");

ALTER TABLE "utenti" ADD FOREIGN KEY ("ruolo_id") REFERENCES "ruoli" ("id");

ALTER TABLE "preferiti" ADD FOREIGN KEY ("utente_id") REFERENCES "utenti" ("id");

ALTER TABLE "preferiti" ADD FOREIGN KEY ("prodotto_id") REFERENCES "prodotti" ("id");
